"""Arm 3 confuser set: how often each system falls for the misleading feature. Descriptive; the shared analysis
(results/arm3_confuser/analysis.json) keeps exact accuracy by confuser type.

    python scripts\\run_categorical.py arm3_confuser analyze
    python scripts\\arm3_confuser_misread.py

Types 1-4: each report stores its misread level, the level a reader who falls for the feature gives. Per system and
type: correct, misread (the answer is the misread level), other wrong, unusable. Control: how often the same system
gives that same level on the main reports of the report's true level in the main run (names version, main pass),
averaged over the type's reports. Type 5 (the stage does not change): correct per feature.
Type 6: the main reports with tumour deposits beside involved nodes, tagged with the level a reader who adds the
deposits to the node count gives (data/arm3/confuser_type6.csv); from the main run's answers, no new call. Counts only
(20 reports a type). Writes results/arm3_confuser/misread.json and misread_tables.md. No network, no model call."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
import pandas as pd

CONFUSERS = "data/arm3/confuser_reports.jsonl"
TYPE6 = "data/arm3/confuser_type6.csv"
CONF_CALLS = "results/arm3_confuser/calls.parquet"
MAIN_CALLS = "results/arm3/calls.parquet"
OUT = "results/arm3_confuser"


def outcome(calls: pd.DataFrame) -> pd.DataFrame:
    """calls with `level` (truth) and `misread_level` (None where no misread applies): adds correct, misread, other,
    unusable, one of them true per row."""
    c = calls.copy()
    ok = c.valid.fillna(False).astype(bool)
    c["unusable"] = ~ok
    c["correct"] = ok & (c.answer == c.level)
    c["misread"] = ok & c.misread_level.notna() & (c.answer == c.misread_level) & ~c.correct
    c["other"] = ok & ~c.correct & ~c.misread
    return c


def control_rate(reports: pd.DataFrame, main: pd.DataFrame, system: str) -> float | None:
    """Mean over the reports of the share of `system`'s main-run answers, on main reports with the report's true
    level, that equal the report's misread level (unusable answers count as not equal)."""
    m = main[main.system == system]
    rates = []
    for level, mis in zip(reports.level, reports.misread_level):
        g = m[m.truth == level]
        if len(g):
            rates.append(float((g.valid.fillna(False).astype(bool) & (g.answer == mis)).mean()))
    return sum(rates) / len(rates) if rates else None


def counts(c: pd.DataFrame) -> dict:
    return {"n": int(len(c)), **{k: int(c[k].sum()) for k in ("correct", "misread", "other", "unusable")}}


def analyse(conf_calls, reports, main, type6, systems, main_systems) -> dict:
    c = outcome(conf_calls.merge(reports[["report_id", "level", "confuser_type", "confuser_feature", "misread_level"]],
                                 left_on="item_id", right_on="report_id"))
    out = {"types_1_4": {}, "type_5": {}, "type_6": {}}
    for t in (1, 2, 3, 4):
        ct = c[c.confuser_type == t]
        reps = reports[reports.confuser_type == t]
        out["types_1_4"][str(t)] = {"feature": str(reps.confuser_feature.iloc[0]), "systems": {
            s: {**counts(ct[ct.system == s]), "control_same_level_main": control_rate(reps, main, s)} for s in systems}}
    c5 = c[c.confuser_type == 5]
    for f, g in c5.groupby("confuser_feature"):
        out["type_5"][str(f)] = {s: counts(g[g.system == s]) for s in systems}
    t6 = type6.assign(misread_level=type6.misread_level.where(type6.misread_changes_level == "True"))
    m6 = outcome(main.drop(columns=["truth"]).merge(t6[["report_id", "level", "misread_level", "misread_changes_level"]],
                                                    left_on="item_id", right_on="report_id"))
    for key, g in (("changes_level", m6[m6.misread_changes_level == "True"]),
                   ("level_unchanged", m6[m6.misread_changes_level != "True"])):
        out["type_6"][key] = {s: counts(g[g.system == s]) for s in main_systems}
    return out


def _cell(d: dict, k: str) -> str:
    return f"{d[k]} of {d['n']}"


def tables(res: dict, systems, main_systems) -> str:
    L = ["# Arm 3 confuser set: falling for the misleading feature", "",
         "Generated by `scripts/arm3_confuser_misread.py` from `results/arm3_confuser/misread.json`; do not edit by "
         "hand. Descriptive; counts of reports. Misread: the answer is the level a reader who falls for the feature "
         "gives. Control: the share of the system's main-run answers, on main reports of the same true level, "
         "that give that same level.", ""]
    for t, blk in res["types_1_4"].items():
        L += [f"## Type {t}: {blk['feature']}", "",
              "| System | Correct | Misread | Other wrong | Unusable | Control: same level in the main run |",
              "|---|---|---|---|---|---|"]
        for s in systems:
            d = blk["systems"][s]
            cr = d["control_same_level_main"]
            L.append(f"| {s} | {_cell(d, 'correct')} | {_cell(d, 'misread')} | {_cell(d, 'other')} | "
                     f"{_cell(d, 'unusable')} | {'–' if cr is None else f'{cr:.0%}'} |")
        L.append("")
    L += ["## Type 5: features that do not change the stage (correct)", "",
          "| System | " + " | ".join(res["type_5"]) + " |", "|---|" + "---|" * len(res["type_5"])]
    for s in systems:
        L.append(f"| {s} | " + " | ".join(_cell(res["type_5"][f][s], "correct") for f in res["type_5"]) + " |")
    L += ["", "## Type 6: tumour deposits beside involved nodes (main run's answers, main reports)", "",
          "Changes level: adding the deposits to the node count moves the report to another level. Level unchanged: "
          "it does not.", "",
          "| System | Changes level: correct | Changes level: misread | Level unchanged: correct |", "|---|---|---|---|"]
    for s in main_systems:
        a, b = res["type_6"]["changes_level"][s], res["type_6"]["level_unchanged"][s]
        L.append(f"| {s} | {_cell(a, 'correct')} | {_cell(a, 'misread')} | {_cell(b, 'correct')} |")
    return "\n".join(L) + "\n"


def main() -> int:
    import run_categorical as RC
    from jevity import categorical as K
    reports = pd.read_json(ROOT / CONFUSERS, lines=True)
    type6 = pd.read_csv(ROOT / TYPE6, dtype=str)
    conf = pd.read_parquet(ROOT / CONF_CALLS)
    main_calls = pd.read_parquet(ROOT / MAIN_CALLS)
    items, systems_main, *_ = RC.design(K.load_arm("arm3"))
    truth = RC.items_frame(items, "names")[["item_id", "truth"]]
    main_calls = main_calls[(main_calls.variant == "names") & (main_calls.repeat == 0)].merge(truth, on="item_id")
    _, systems, *_ = RC.design(K.load_arm("arm3_confuser"))
    res = analyse(conf, reports, main_calls, type6, systems, systems_main)
    res = {"note": "descriptive; counts of reports", **res}
    out = ROOT / OUT
    (out / "misread.json").write_text(json.dumps(res, indent=1) + "\n", encoding="utf-8")
    (out / "misread_tables.md").write_text(tables(res, systems, systems_main), encoding="utf-8", newline="\n")
    print(f"wrote misread.json and misread_tables.md under {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
